### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  usv:   192.168.147.211
  suav:  192.168.147.21
  suavmini: 192.168.147.22
  tuav1: 192.168.147.31
  tuav2: 192.168.147.42
  tuav3: 192.168.147.43
  arm: 192.168.147.168
  tuav6: 192.168.147.61
  local: 127.0.0.1 # just for local machine test

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics: 
- topic_name: /tuav2_takeoff_flag
  msg_type: std_msgs/Int8
  max_freq: 1
  srcIP: self
  srcPort: 3101

- topic_name: /tuav3_takeoff_flag
  msg_type: std_msgs/Int8
  max_freq: 1
  srcIP: self
  srcPort: 3102

- topic_name: /tuav1/state
  msg_type: std_msgs/String
  max_freq: 20
  srcIP: self
  srcPort: 1010

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /usv/mavros/imu
  msg_type: sensor_msgs/Imu 
  srcIP: usv 
  srcPort: 1101 

- topic_name: /tuav1_takeoff_flag
  msg_type: std_msgs/Int8
  srcIP: usv 
  srcPort: 1102

- topic_name: /target_lidar_position
  msg_type: geometry_msgs/Pose2D
  srcIP: usv
  srcPort: 1107

- topic_name: /arm/state
  msg_type: std_msgs/String
  srcIP: arm
  srcPort: 1010

- topic_name: /suav/state
  msg_type: std_msgs/String
  srcIP: suav
  srcPort: 1010

- topic_name: /tuav2/state
  msg_type: std_msgs/String
  srcIP: tuav2
  srcPort: 1010

- topic_name: /tuav3/state
  msg_type: std_msgs/String
  srcIP: tuav3
  srcPort: 1010

- topic_name: /tuav6/state
  msg_type: std_msgs/String
  srcIP: tuav6
  srcPort: 1010

- topic_name: /usv/state
  msg_type: std_msgs/String
  srcIP: usv
  srcPort: 1010
