### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  usv:   192.168.147.211
  suav:  192.168.147.21
  tuav1: 192.168.147.31
  tuav2: 192.168.2.102
  tuav3: 192.168.2.103
  arm: 192.168.147.168
  local: 127.0.0.1 # just for local machine test

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /usv/largebox_pos
  msg_type: geometry_msgs/Vector3
  max_freq: 60
  srcIP: self
  srcPort: 1101

- topic_name: /usv/usvarm_detect
  msg_type: std_msgs/Int8.h
  max_freq: 20
  srcIP: self
  srcPort: 1102

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /tuav1/single_task_finish
  msg_type: std_msgs/Int8.h
  srcIP: tuav1
  srcPort: 3101

