### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  usv:   192.168.147.211
  suav:  192.168.147.21
  suavmini: 192.168.147.22
  tuav1: 192.168.147.31
  tuav2: 192.168.147.42
  tuav3: 192.168.147.43
  arm: 192.168.147.168
  tuav6: 192.168.147.61
  local: 127.0.0.1 # just for local machine test

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /suav/pod/target_nav_position
  msg_type: geometry_msgs/PoseStamped
  max_freq: 20
  srcIP: self
  srcPort: 2101

- topic_name: /suav/pod/usv_nav_position
  msg_type: geometry_msgs/PoseStamped
  max_freq: 20
  srcIP: self
  srcPort: 2102

- topic_name: /suav/uavState
  msg_type: std_msgs/Int8
  max_freq: 50
  srcIP: self
  srcPort: 2103


####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /usv/suav_land_flag
  msg_type: std_msgs/Int8
  srcIP: usv
  srcPort: 1102
