IP:
  self: '*'
  usv:   192.168.147.211
  suav:  192.168.147.21
  suavmini: 192.168.147.22
  tuav1: 192.168.147.31
  tuav2: 192.168.147.42
  tuav3: 192.168.147.43
  arm: 192.168.147.168
  tuav6: 192.168.147.61
  tuav8: 192.168.147.81
  streamer: 192.168.147.99
  local: 127.0.0.1

send_topics:

- topic_name: /tuav8/state
  msg_type: std_msgs/String
  max_freq: 20
  srcIP: self
  srcPort: 10010

recv_topics:
- topic_name: /arm/state
  msg_type: std_msgs/String
  srcIP: arm
  srcPort: 10010

- topic_name: /suav/state
  msg_type: std_msgs/String
  srcIP: suav
  srcPort: 10010

- topic_name: /tuav1/state
  msg_type: std_msgs/String
  srcIP: tuav1
  srcPort: 10010

- topic_name: /tuav2/state
  msg_type: std_msgs/String
  srcIP: tuav2
  srcPort: 10010

- topic_name: /tuav3/state
  msg_type: std_msgs/String
  srcIP: tuav3
  srcPort: 10010
  
  topic_name: /tuav6/state
  msg_type: std_msgs/String
  srcIP: tuav6
  srcPort: 10010

- topic_name: /usv/state
  msg_type: std_msgs/String
  srcIP: usv
  srcPort: 10010
  
  topic_name: /target_lidar_position
  msg_type: geometry_msgs/Pose2D
  srcIP: usv
  srcPort: 1107
  
- topic_name: /usv/compass
  msg_type: sensor_msgs/Imu
  srcIP: usv
  srcPort: 1101
